import type { ContextGraph, WikiSearchResult } from '../types';

/** The real Wikipedia article behind the example (used when regenerating it at a different scale) */
export const chillanExampleArticle: WikiSearchResult = {
  title: '1939 Chillán earthquake',
  description: '',
  pageId: 0,
  url: 'https://en.wikipedia.org/wiki/1939_Chill%C3%A1n_earthquake',
};

/**
 * Built-in example: the 1939 Chillán earthquake at Generational scale.
 * Generated by ContextMap itself, so it shows what a real result looks like.
 */
export const chillanExample: ContextGraph = {
  "title": "Disaster and Development: The 1939 Chillán Earthquake",
  "summary": "The 1939 Chillán earthquake remains the deadliest seismic event in Chilean history, serving as a critical catalyst for the nation's modernization and institutional reform. In the immediate aftermath, President Pedro Aguirre Cerda used the crisis to establish CORFO, a massive state corporation that drove Chile's industrialization for decades. The destruction also necessitated a complete rethink of urban planning, turning cities like Chillán into laboratories for modernist, earthquake-resistant architecture. On an international level, the disaster prompted a record-breaking U.S. humanitarian airlift, signaling the growing strategic importance of long-range aviation. This map explores how a single night of tectonic violence reshaped Chile's economic, physical, and political landscape throughout the 20th century.",
  "subjectKind": "event",
  "window": {
    "label": "1864 – 1989",
    "startYear": 1864,
    "endYear": 1989,
    "anchorYear": 1939
  },
  "nodes": [
    {
      "id": "chillan_earthquake_1939",
      "label": "1939 Chillán earthquake",
      "kind": "subject",
      "year": "1939",
      "startYear": 1939,
      "hook": "This remains the deadliest natural disaster in Chilean history, claiming roughly 28,000 lives in a single night.",
      "summary": "Occurring on January 24, 1939, this magnitude 8.3 earthquake devastated south-central Chile, particularly the cities of Chillán and Concepción. The event occurred shortly after the election of the Popular Front government, creating an immediate political and humanitarian crisis. Its extreme death toll was attributed to the failure of traditional masonry buildings, which led to a total overhaul of national construction standards and the birth of state-led economic development.",
      "wikipediaUrl": "https://en.wikipedia.org/wiki/1939_Chill%C3%A1n_earthquake"
    },
    {
      "id": "talca_earthquake_1928",
      "label": "1928 Talca earthquake",
      "kind": "cause",
      "year": "1928",
      "startYear": 1928,
      "hook": "This earlier quake led to Chile's first mandatory seismic building codes, which were tragically insufficient in 1939.",
      "summary": "The 1928 earthquake prompted the Chilean government to pass the first 'General Law of Urbanism and Construction' in 1929. However, the 1939 Chillán quake demonstrated that these early regulations were poorly enforced and inadequate for major subduction events. The failure of buildings in 1939 that had nominally followed the 1928 codes led to much stricter reinforcement requirements for concrete structures.",
      "wikipediaUrl": "https://en.wikipedia.org/wiki/1928_Talca_earthquake"
    },
    {
      "id": "pedro_aguirre_cerda",
      "label": "Pedro Aguirre Cerda",
      "kind": "person",
      "year": "1938–1941",
      "startYear": 1938,
      "hook": "The 'President of the Poor' who transformed a national tragedy into an engine for Chilean industrialization.",
      "summary": "Elected as the leader of the Popular Front just months before the earthquake, Aguirre Cerda faced the monumental task of rebuilding the country. He argued that reconstruction must go beyond masonry and address the root causes of Chilean poverty and underdevelopment. His administration used the emergency to push through radical legislation that established the state as the primary driver of the economy.",
      "wikipediaUrl": "https://en.wikipedia.org/wiki/Pedro_Aguirre_Cerda",
      "endYear": 1941
    },
    {
      "id": "corfo",
      "label": "CORFO",
      "kind": "consequence",
      "year": "1939",
      "startYear": 1939,
      "hook": "Born from the rubble of Chillán, this agency became the powerhouse of the Chilean state economy.",
      "summary": "The Production Development Corporation (CORFO) was established in April 1939 as a direct response to the earthquake. While its initial mission was reconstruction, it rapidly expanded to fund steel mills, electricity grids, and oil exploration. It represented a shift toward state-managed capitalism that defined Chilean economic policy until the 1970s.",
      "wikipediaUrl": "https://en.wikipedia.org/wiki/CORFO"
    },
    {
      "id": "boeing_xb_15",
      "label": "Boeing XB-15 'Flight of Mercy'",
      "kind": "idea",
      "year": "1939",
      "startYear": 1939,
      "hook": "A massive experimental bomber was repurposed for a record-breaking humanitarian flight to Chile.",
      "summary": "In February 1939, the U.S. Army Air Corps sent the XB-15 prototype on a 5,000-mile non-stop flight to deliver medical supplies to earthquake victims. This mission was a major propaganda success for the United States, demonstrating the reach of its aviation technology. It also served as a practical test for long-range heavy bombers just months before the outbreak of World War II.",
      "wikipediaUrl": "https://en.wikipedia.org/wiki/Boeing_XB-15"
    },
    {
      "id": "caleb_v_haynes",
      "label": "Caleb V. Haynes",
      "kind": "person",
      "year": "1939",
      "startYear": 1939,
      "hook": "The pilot who earned the Mackay Trophy for delivering aid to Chile across two continents.",
      "summary": "Major Caleb Haynes commanded the XB-15 during its 1939 relief mission to Santiago. His successful navigation of the long-distance route proved the feasibility of rapid international disaster response by air. Haynes went on to become a key figure in the U.S. Air Transport Command during the war, utilizing the experience gained in the 'Flight of Mercy.'",
      "wikipediaUrl": "https://en.wikipedia.org/wiki/Caleb_V._Haynes"
    },
    {
      "id": "modernist_architecture_chile",
      "label": "Modernist Architecture in Chile",
      "kind": "idea",
      "year": "c. 1930s–1960s",
      "startYear": 1930,
      "hook": "The destruction of traditional cities allowed Chile to become a global leader in modernist urban design.",
      "summary": "After 1939, the reconstruction of Chillán and Concepción rejected colonial-style adobe and masonry in favor of reinforced concrete and functionalist design. International trends in Modernism were adopted to prioritize public health, seismic safety, and speed of construction. This period gave rise to a unique Chilean architectural identity characterized by clean lines and structural honesty.",
      "wikipediaUrl": "https://en.wikipedia.org/wiki/Architecture_of_Chile",
      "endYear": 1969
    },
    {
      "id": "chillan_cathedral",
      "label": "Cathedral of Chillán",
      "kind": "place",
      "year": "1939–1950",
      "startYear": 1939,
      "hook": "An iconic concrete structure designed specifically to withstand the earth's most violent movements.",
      "summary": "Designed by architect Hernán Larraín Errázuriz, the new cathedral replaced the one destroyed in 1939. Its distinctive parabolic arches were engineered for maximum seismic stability, departing from traditional ecclesiastical forms. It remains a symbol of the city's resilience and its embrace of mid-century modern engineering after the disaster.",
      "wikipediaUrl": "https://en.wikipedia.org/wiki/St._Bartholomew_Cathedral%2C_Chill%C3%A1n"
    },
    {
      "id": "isi_policy",
      "label": "Import Substitution Industrialization",
      "kind": "idea",
      "year": "1930s–1980s",
      "startYear": 1930,
      "hook": "The earthquake accelerated Chile's move away from foreign dependency toward self-sufficiency.",
      "summary": "Import Substitution Industrialization (ISI) became the dominant economic doctrine in Latin America, and the 1939 quake served as its catalyst in Chile. By creating CORFO to rebuild, the government began manufacturing goods locally that were previously imported. This policy shaped the Chilean middle class and urban labor movements for nearly half a century.",
      "wikipediaUrl": "https://en.wikipedia.org/wiki/Import_substitution_industrialization",
      "endYear": 1989
    },
    {
      "id": "valdivia_earthquake_1960",
      "label": "1960 Valdivia earthquake",
      "kind": "parallel",
      "year": "1960",
      "startYear": 1960,
      "hook": "The most powerful earthquake ever recorded, which tested the lessons learned in 1939.",
      "summary": "While the 1960 Great Chilean Earthquake had a much higher magnitude (9.5), its death toll was significantly lower than the 1939 Chillán event. This difference is often attributed to the improved building codes and reinforced concrete standards implemented after 1939. The 1960 event further solidified Chile's global expertise in seismic engineering and disaster management.",
      "wikipediaUrl": "https://en.wikipedia.org/wiki/1960_Valdivia_earthquake"
    },
    {
      "id": "onemi",
      "label": "ONEMI",
      "kind": "consequence",
      "year": "1974",
      "startYear": 1974,
      "hook": "Chile's specialized disaster response office is the institutional legacy of a century of quakes.",
      "summary": "The National Emergency Office of the Ministry of the Interior (ONEMI) was established to centralize disaster response, a need first identified during the 1939 and 1960 recoveries. It evolved from the earlier 'Civil Defense' structures created during the 1939 reconstruction. ONEMI represents the final institutionalization of the hard-won lessons regarding logistics and public safety from the Chillán disaster."
    },
    {
      "id": "san_juan_earthquake_1944",
      "label": "1944 San Juan earthquake",
      "kind": "parallel",
      "year": "1944",
      "startYear": 1944,
      "hook": "A similar disaster in Argentina that also led to massive state expansion and political upheaval.",
      "summary": "Much like the Chillán earthquake, the 1944 event in San Juan, Argentina, served as a turning point for state-led reconstruction and social policy. In Argentina, the disaster relief effort was spearheaded by Juan Perón, helping to launch his political career. Both events illustrate how mid-century Latin American governments used seismic tragedies to consolidate power and modernize infrastructure.",
      "wikipediaUrl": "https://en.wikipedia.org/wiki/1944_San_Juan_earthquake"
    }
  ],
  "edges": [
    {
      "source": "talca_earthquake_1928",
      "target": "chillan_earthquake_1939",
      "label": "failed codes led to deaths"
    },
    {
      "source": "chillan_earthquake_1939",
      "target": "pedro_aguirre_cerda",
      "label": "major crisis for new president"
    },
    {
      "source": "pedro_aguirre_cerda",
      "target": "corfo",
      "label": "founded the agency"
    },
    {
      "source": "chillan_earthquake_1939",
      "target": "corfo",
      "label": "triggered emergency creation"
    },
    {
      "source": "corfo",
      "target": "isi_policy",
      "label": "primary vehicle for industrialization"
    },
    {
      "source": "chillan_earthquake_1939",
      "target": "boeing_xb_15",
      "label": "required international relief"
    },
    {
      "source": "boeing_xb_15",
      "target": "caleb_v_haynes",
      "label": "piloted the mission"
    },
    {
      "source": "chillan_earthquake_1939",
      "target": "modernist_architecture_chile",
      "label": "cleared space for modernism"
    },
    {
      "source": "modernist_architecture_chile",
      "target": "chillan_cathedral",
      "label": "exemplary seismic design"
    },
    {
      "source": "chillan_earthquake_1939",
      "target": "valdivia_earthquake_1960",
      "label": "set mortality benchmark"
    },
    {
      "source": "chillan_earthquake_1939",
      "target": "onemi",
      "label": "long-term institutional result"
    },
    {
      "source": "chillan_earthquake_1939",
      "target": "san_juan_earthquake_1944",
      "label": "shared regional patterns"
    }
  ]
};
